# Generated by Django 5.0.6 on 2024-05-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='text',
            new_name='address',
        ),
    ]
